### ISSUE TITLE
Nemoguce pokrenuti login formu

### ISSUE THREAD

**Issue by eminamuharemovic** [SoftverInzenjeringETFSA/SI2014Tim10#36]
Komponenta:
glavna-knjiga

commit ID:
f6cfbc465175f1a7332fd9b3ea8c8f0c67f35c54

Opis problema:
Nemoguce pokrenuti login formu

Koraci za reproduciranje problema:
1. Desni klik na LoginFrame -> Run

Dobijeni rezultat:
- Ne moze se pokrenuti forma:

```
Exception in thread "AWT-EventQueue-0" java.lang.Error: Unresolved compilation problem: 
    The method run() of type new Runnable(){} must override a superclass method

    at com.tim10.glavna_knjiga.windows.LoginFrame$1.run(LoginFrame.java:56)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
```

Očekivani rezultat:
- Forma se pokrece bez problema

**Comment by mnuhodzic** [comment]
nije moguce reproducirati,a vec postoji takav slican issue  #32
