### ISSUE TITLE
Nemoguć login korisnika kao administratora

### ISSUE THREAD

**Issue by AdnaDurakovic** [SoftverInzenjeringETFSA/SI2014Tim10#64]
Komponenta:
LoginFrame

commit ID:
3c3eaa2

Opis problema:
Nemoguć login korisnika kao administratora

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju klikom na Run->”LoginFrame”.
2. U polje “Korisničko ime” unijeti “tms1337”.
3. U polje “Lozinka” unijeti “44253432”.
4. Kao “Tip korisnika” odabrati “Administrator”.
5. Kliknuti na button “Uloguj se!”.

Dobijeni rezultat:
- Klik na button “Uloguj se!” ne radi. Ispisuje se sljedeća greška u konzolnom prozoru:

Hibernate: select korisnik0_.Id as Id1_6_, korisnik0_.KorisnikTipovi_Id as Korisnik2_6_, korisnik0_.Ime as Ime3_6_, korisnik0_.Prezime as Prezime4_6_, korisnik0_.KorisnickoIme as Korisnic5_6_, korisnik0_.Lozinka as Lozinka6_6_, korisnik0_.Adresa as Adresa7_6_, korisnik0_.JMBG as JMBG8_6_, korisnik0_.Telefon as Telefon9_6_, korisnik0_.Fax as Fax10_6_, korisnik0_.Email as Email11_6_ from Tim10.Korisnik korisnik0_ where korisnik0_.KorisnickoIme=?
Hibernate: select korisnik0_.Id as Id1_6_, korisnik0_.KorisnikTipovi_Id as Korisnik2_6_, korisnik0_.Ime as Ime3_6_, korisnik0_.Prezime as Prezime4_6_, korisnik0_.KorisnickoIme as Korisnic5_6_, korisnik0_.Lozinka as Lozinka6_6_, korisnik0_.Adresa as Adresa7_6_, korisnik0_.JMBG as JMBG8_6_, korisnik0_.Telefon as Telefon9_6_, korisnik0_.Fax as Fax10_6_, korisnik0_.Email as Email11_6_ from Tim10.Korisnik korisnik0_ where korisnik0_.KorisnickoIme=?
Hibernate: select korisnik0_.Id as Id1_6_, korisnik0_.KorisnikTipovi_Id as Korisnik2_6_, korisnik0_.Ime as Ime3_6_, korisnik0_.Prezime as Prezime4_6_, korisnik0_.KorisnickoIme as Korisnic5_6_, korisnik0_.Lozinka as Lozinka6_6_, korisnik0_.Adresa as Adresa7_6_, korisnik0_.JMBG as JMBG8_6_, korisnik0_.Telefon as Telefon9_6_, korisnik0_.Fax as Fax10_6_, korisnik0_.Email as Email11_6_ from Tim10.Korisnik korisnik0_
2
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at com.tim10.glavna_knjiga.dbutils.HomeFrameAdminUtils.getDefModel(HomeFrameAdminUtils.java:65)
    at com.tim10.glavna_knjiga.windows.HomeFrameAdmin.<init>(HomeFrameAdmin.java:37)
    at com.tim10.glavna_knjiga.windows.LoginFrame.checkLoginAndGo(LoginFrame.java:239)
    at com.tim10.glavna_knjiga.windows.LoginFrame.access$0(LoginFrame.java:215)
    at com.tim10.glavna_knjiga.windows.LoginFrame$8.mouseClicked(LoginFrame.java:180)
    at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

Očekivani rezultat:
- Očekuje se otvaranje forme “HomeFrameAdmin”.

**Comment by tms1337** [comment]
nije valjana situacija u bazi, jmbg atribut bude 0 i zato se desi bug. 
nacin ispravke je da se u bazi populateju polja za koje se pretpostavlja da nisu null.

**Comment by mnuhodzic** [comment]
Ovo je duplikat, vec prijavljen ovaj issue #32
